dev_build_case_study_orchestrator:
  stage: build
  only:
    refs:
      - develop
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "172.16.11.24:5000"
  script:
    - echo "Building case_study_orchestrator dev..."
    - cd case_study_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-case-study-orchestrator .
    - rm -rf core
    - docker tag leo-etl-case-study-orchestrator ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-case-study-orchestrator:dev
    - docker push ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-case-study-orchestrator:dev
  tags:
  - docker

dev_deploy_case_study_orchestrator:
  stage: deploy
  only:
    refs:
      - develop
    changes:
      - core/*
      - case_study_orchestrator/*
  script:
    - echo "Deploying case_study_orchestrator dev..."
    - cd /home/hienhoang/leonardo/master/dev_master/dev_case_study_orchestrator
    - docker-compose pull
    - docker-compose up -d
  tags:
  - ssh

qc_build_case_study_orchestrator:
  stage: build
  only:
    refs:
      - qc
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Building case_study_orchestrator dev..."
    - cat /credentials/qc-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd case_study_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-case-study-orchestrator .
    - rm -rf core
    - docker tag leo-etl-case-study-orchestrator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:qc
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:qc
  tags:
  - docker

qc_deploy_case_study_orchestrator:
  stage: deploy
  only:
    refs:
      - qc
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Deploying case_study_orchestrator qc..."
    - gcloud auth activate-service-account --key-file /credentials/qc-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@orchestrator --zone=us-central1-a --quiet -- "cd case_study_orchestrator && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud

stag_build_case_study_orchestrator:
  stage: build
  only:
    refs:
      - stag
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Building case_study_orchestrator stag..."
    - cat /credentials/stg-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd case_study_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-case-study-orchestrator .
    - rm -rf core
    - docker tag leo-etl-case-study-orchestrator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:stag
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:stag
  tags:
  - docker

stag_deploy_case_study_orchestrator:
  stage: deploy
  only:
    refs:
      - stag
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Deploying case_study_orchestrator stag..."
    - gcloud auth activate-service-account --key-file /credentials/stg-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@orchestrator --zone=us-central1-a --quiet -- "cd case_study_orchestrator && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud

prod_build_case_study_orchestrator:
  stage: build
  only:
    refs:
      - prod
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "valid-aquifer-305408"
  script:
    - echo "Building case_study_orchestrator prod..."
    - cat /credentials/prod-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd case_study_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-case-study-orchestrator .
    - rm -rf core
    - docker tag leo-etl-case-study-orchestrator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:prod
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:prod
  tags:
  - docker

fresh_build_case_study_orchestrator:
  stage: build
  environment:
    name: fresh
  only:
    refs:
      - fresh
    changes:
      - core/*
      - case_study_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "data-web-fresh"
  script:
    - echo "Building case_study_orchestrator fresh..."
    - cat /credentials/fresh-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd case_study_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-case-study-orchestrator .
    - rm -rf core
    - docker tag leo-etl-case-study-orchestrator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:fresh
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-case-study-orchestrator:fresh
  tags:
  - docker
