
dev_build_translation_worker:
  stage: build
  only:
    refs:
      - develop
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "172.16.11.24:5000"
  script:
    - echo "Building scalable_translation_worker dev..."
    - cd scalable_translation_worker
    - cp -r ../core core
    - docker build -t leo-etl-translator .
    - rm -rf core
    - docker tag leo-etl-translator ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-translator:dev
    - docker push ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-translator:dev
  tags:
  - docker

dev_deploy_translation_worker:
  stage: deploy
  only:
    refs:
      - develop
    changes:
      - core/*
      - scalable_translation_worker/*
  script:
    - echo "Deploying scalable_translation_worker dev..."
    - cd /home/hienhoang/leonardo/worker/dev_worker/
    - docker-compose pull
    - docker-compose up -d
  tags:
  - ssh

qc_build_translation_worker:
  stage: build
  only:
    refs:
      - qc
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Building scalable_translation_worker qc..."
    - cat /credentials/qc-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_translation_worker
    - cp -r ../core core
    - docker build -t leo-etl-translator .
    - rm -rf core
    - docker tag leo-etl-translator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:qc
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:qc
  tags:
  - docker

qc_deploy_translation_worker:
  stage: deploy
  only:
    refs:
      - qc
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Deploying scalable_translation_worker dev..."
    - gcloud auth activate-service-account --key-file /credentials/qc-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@worker --zone=us-central1-a --quiet -- "cd worker && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud

stag_build_translation_worker:
  stage: build
  only:
    refs:
      - stag
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Building scalable_translation_worker stag..."
    - cat /credentials/stg-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_translation_worker
    - cp -r ../core core
    - docker build -t leo-etl-translator .
    - rm -rf core
    - docker tag leo-etl-translator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:stag
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:stag
  tags:
  - docker

stag_deploy_translation_worker:
  stage: deploy
  only:
    refs:
      - stag
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Deploying scalable_translation_worker stag..."
    - gcloud auth activate-service-account --key-file /credentials/stg-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@worker --zone=us-central1-a --quiet -- "cd worker && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud

prod_build_translation_worker:
  stage: build
  only:
    refs:
      - prod
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "valid-aquifer-305408"
  script:
    - echo "Building scalable_translation_worker prod..."
    - cat /credentials/prod-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_translation_worker
    - cp -r ../core core
    - docker build -t leo-etl-translator .
    - rm -rf core
    - docker tag leo-etl-translator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:prod
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:prod
  tags:
  - docker

fresh_build_translation_worker:
  stage: build
  environment:
    name: fresh
  only:
    refs:
      - fresh
    changes:
      - core/*
      - scalable_translation_worker/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "data-web-fresh"
  script:
    - echo "Building scalable_translation_worker fresh..."
    - cat /credentials/fresh-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_translation_worker
    - cp -r ../core core
    - docker build -t leo-etl-translator .
    - rm -rf core
    - docker tag leo-etl-translator ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:fresh
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-translator:fresh
  tags:
  - docker