
dev_build_dq_process_monitoring:
  stage: build
  only:
    refs:
      - develop
    changes:
      - core/*
      - dq_process_monitoring/*
  variables:
    CONTAINER_REGISTRY: "172.16.11.24:5000"
  script:
    - echo "Building dq_process_monitoring dev..."
    - cd dq_process_monitoring
    - cp -r ../core core
    - docker build -t leo-dq-process-monitoring .
    - rm -rf core
    - docker tag leo-dq-process-monitoring ${CONTAINER_REGISTRY}/leo-etlplatform/leo-dq-process-monitoring:dev
    - docker push ${CONTAINER_REGISTRY}/leo-etlplatform/leo-dq-process-monitoring:dev
  tags:
  - docker

dev_deploy_dq_process_monitoring:
  stage: deploy
  only:
    refs:
      - develop
    changes:
      - core/*
      - dq_process_monitoring/*
  script:
    - echo "Deploying dq_process_monitoring dev..."
    - cd /home/hienhoang/leonardo/master/dev_master/dev_company_datasource_orchestrator
    - docker-compose pull
    - docker-compose up -d
  tags:
  - ssh


stag_build_dq_process_monitoring:
  stage: build
  only:
    refs:
      - stag
    changes:
      - core/*
      - dq_process_monitoring/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Building dq_process_monitoring stag..."
    - cat /credentials/stg-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd dq_process_monitoring
    - cp -r ../core core
    - docker build -t leo-dq-process-monitoring .
    - rm -rf core
    - docker tag leo-dq-process-monitoring ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-dq-process-monitoring:stag
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-dq-process-monitoring:stag
  tags:
  - docker

stag_deploy_dq_process_monitoring:
  stage: deploy
  only:
    refs:
      - stag
    changes:
      - core/*
      - dq_process_monitoring/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Deploying dq_process_monitoring stag..."
    - gcloud auth activate-service-account --key-file /credentials/stg-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@orchestrator --zone=us-central1-a --quiet -- "cd company_datasource_orchestrator && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud


prod_build_dq_process_monitoring:
  stage: build
  only:
    refs:
      - prod
    changes:
      - core/*
      - dq_process_monitoring/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "valid-aquifer-305408"
  script:
    - echo "Building dq_process_monitoring prod..."
    - cat /credentials/prod-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd dq_process_monitoring
    - cp -r ../core core
    - docker build -t leo-dq-process-monitoring .
    - rm -rf core
    - docker tag leo-dq-process-monitoring ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-dq-process-monitoring:prod
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-dq-process-monitoring:prod
  tags:
  - docker
