dev_build_company_datasource_orchestrator:
  stage: build
  only:
    refs:
      - develop
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "172.16.11.24:5000"
  script:
    - echo "Building company_datasource_orchestrator dev..."
    - cd company_datasource_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-master .
    - rm -rf core
    - docker tag leo-etl-master ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-master:dev
    - docker push ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-master:dev
  tags:
    - docker

dev_deploy_company_datasource_orchestrator:
  stage: deploy
  only:
    refs:
      - develop
    changes:
      - core/*
      - company_datasource_orchestrator/*
  script:
    - echo "Deploying company_datasource_orchestrator dev..."
    - cd /home/hienhoang/leonardo/master/dev_master/dev_company_datasource_orchestrator
    - docker-compose pull
    - docker-compose up -d
  tags:
    - ssh

qc_build_company_datasource_orchestrator:
  stage: build
  only:
    refs:
      - qc
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Building company_datasource_orchestrator dev..."
    - cat /credentials/qc-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd company_datasource_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-master .
    - rm -rf core
    - docker tag leo-etl-master ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:qc
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:qc
  tags:
    - docker

qc_deploy_company_datasource_orchestrator:
  stage: deploy
  only:
    refs:
      - qc
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Deploying company_datasource_orchestrator qc..."
    - gcloud auth activate-service-account --key-file /credentials/qc-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@orchestrator --zone=us-central1-a --quiet -- "cd company_datasource_orchestrator && docker-compose pull && docker-compose up -d"
  tags:
    - gcloud

stag_build_company_datasource_orchestrator:
  stage: build
  only:
    refs:
      - stag
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Building company_datasource_orchestrator dev..."
    - cat /credentials/stg-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd company_datasource_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-master .
    - rm -rf core
    - docker tag leo-etl-master ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:stag
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:stag
  tags:
    - docker

stag_deploy_company_datasource_orchestrator:
  stage: deploy
  only:
    refs:
      - stag
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Deploying company_datasource_orchestrator stag..."
    - gcloud auth activate-service-account --key-file /credentials/stg-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@orchestrator --zone=us-central1-a --quiet -- "cd company_datasource_orchestrator && docker-compose pull && docker-compose up -d"
  tags:
    - gcloud

prod_build_company_datasource_orchestrator:
  stage: build
  only:
    refs:
      - prod
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "valid-aquifer-305408"
  script:
    - echo "Building company_datasource_orchestrator prod..."
    - cat /credentials/prod-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd company_datasource_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-master .
    - rm -rf core
    - docker tag leo-etl-master ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:prod
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:prod
  tags:
    - docker

fresh_build_company_datasource_orchestrator:
  stage: build
  environment:
    name: fresh
  only:
    refs:
      - fresh
    changes:
      - core/*
      - company_datasource_orchestrator/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "data-web-fresh"
  script:
    - echo "Building company_datasource_orchestrator fresh..."
    - cat /credentials/fresh-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd company_datasource_orchestrator
    - cp -r ../core core
    - docker build -t leo-etl-master .
    - rm -rf core
    - docker tag leo-etl-master ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:fresh
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-master:fresh
  tags:
    - docker
