
dev_build_nlp_indexer:
  stage: build
  only:
    refs:
      - develop
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "172.16.11.24:5000"
  script:
    - echo "Building scalable_nlp_indexer dev..."
    - cd scalable_nlp_indexer
    - cp -r ../core core
    - docker build -t leo-etl-nlp_indexer .
    - rm -rf core
    - docker tag leo-etl-nlp_indexer ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-nlp_indexer:dev
    - docker push ${CONTAINER_REGISTRY}/leo-etlplatform/leo-etl-nlp_indexer:dev
  tags:
  - docker

dev_deploy_nlp_indexer:
  stage: deploy
  only:
    refs:
      - develop
    changes:
      - core/*
      - scalable_nlp_indexer/*
  script:
    - echo "Deploying scalable_nlp_indexer dev..."
    - cd /home/hienhoang/leonardo/worker/dev_worker/
    - docker-compose pull
    - docker-compose up -d
  tags:
  - ssh


qc_build_nlp_indexer:
  stage: build
  only:
    refs:
      - qc
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Building scalable_nlp_indexer qc..."
    - cat /credentials/qc-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_nlp_indexer
    - cp -r ../core core
    - docker build -t leo-etl-nlp_indexer .
    - rm -rf core
    - docker tag leo-etl-nlp_indexer ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:qc
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:qc
  tags:
  - docker

qc_deploy_nlp_indexer:
  stage: deploy
  only:
    refs:
      - qc
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-qc"
  script:
    - echo "Deploying scalable_nlp_indexer qc..."
    - gcloud auth activate-service-account --key-file /credentials/qc-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@worker --zone=us-central1-a --quiet -- "cd worker && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud

stag_build_nlp_indexer:
  stage: build
  only:
    refs:
      - stag
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Building scalable_nlp_indexer stag..."
    - cat /credentials/stg-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_nlp_indexer
    - cp -r ../core core
    - docker build -t leo-etl-nlp_indexer .
    - rm -rf core
    - docker tag leo-etl-nlp_indexer ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:stag
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:stag
  tags:
  - docker

stag_deploy_nlp_indexer:
  stage: deploy
  only:
    refs:
      - stag
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "leo-etl-staging"
  script:
    - echo "Deploying scalable_nlp_indexer stag..."
    - gcloud auth activate-service-account --key-file /credentials/stg-etl-ssh.json
    - gcloud config set project ${GCP_PROJECT}
    - gcloud compute ssh hien_hoang@worker --zone=us-central1-a --quiet -- "cd worker && docker-compose pull && docker-compose up -d"
  tags:
  - gcloud


prod_build_nlp_indexer:
  stage: build
  only:
    refs:
      - prod
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "valid-aquifer-305408"
  script:
    - echo "Building scalable_nlp_indexer prod..."
    - cat /credentials/prod-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_nlp_indexer
    - cp -r ../core core
    - docker build -t leo-etl-nlp_indexer .
    - rm -rf core
    - docker tag leo-etl-nlp_indexer ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:prod
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:prod
  tags:
  - docker

fresh_build_nlp_indexer:
  stage: build
  environment:
    name: fresh
  only:
    refs:
      - fresh
    changes:
      - core/*
      - scalable_nlp_indexer/*
  variables:
    CONTAINER_REGISTRY: "gcr.io"
    GCP_PROJECT: "data-web-fresh"
  script:
    - echo "Building scalable_nlp_indexer fresh..."
    - cat /credentials/fresh-gcr.json | docker login -u _json_key --password-stdin https://${CONTAINER_REGISTRY}
    - cd scalable_nlp_indexer
    - cp -r ../core core
    - docker build -t leo-etl-nlp_indexer .
    - rm -rf core
    - docker tag leo-etl-nlp_indexer ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:fresh
    - docker push ${CONTAINER_REGISTRY}/${GCP_PROJECT}/leo-etl-nlp_indexer:fresh
  tags:
  - docker
